PigMa-HaruSari/be15-4th-PigMa-HaruSari

- backend/build.gradle
Closes #5 
- lombok 추가하기
- mybatis 추가하기
- validation 추가하기
- swagger 추가하기 
- #5
> chore: 프로젝트에 필요한 의존성을 build.gradle에 추가 (#5)

- backend/src/main/resources/application.yml
Closes #7 
- map-underscore-to-camel-case 옵션 추가 
- log-impl 옵션 추가
- mapper-locations 옵션 추가
- type-aliases-package 옵션 추가
- #7
> feat: application.yml에 mybatis 옵션 설정 및 서버 포트를 환경 변수로 처리하도록 수정 (#7)

- backend/build.gradle
- backend/src/main/java/com/pigma/harusari/alarm/command/dto/AlarmCreateDto.java
- backend/src/main/java/com/pigma/harusari/alarm/command/entity/Alarm.java
- backend/src/main/java/com/pigma/harusari/alarm/command/repository/AlarmRepository.java
- backend/src/main/java/com/pigma/harusari/alarm/command/scheduler/AlarmScheduler.java
- backend/src/main/java/com/pigma/harusari/alarm/command/service/AlarmService.java
- backend/src/main/java/com/pigma/harusari/alarm/config/RabbitMQConfig.java
- backend/src/main/java/com/pigma/harusari/alarm/config/SchedulerConfig.java
- backend/src/main/java/com/pigma/harusari/alarm/listener/AlarmListener.java
- backend/src/main/java/com/pigma/harusari/alarm/query/mapper/ScheduleQueryMapper.java
- backend/src/main/java/com/pigma/harusari/alarm/sse/SseController.java
- backend/src/main/java/com/pigma/harusari/alarm/sse/SseService.java
- backend/src/main/java/com/pigma/harusari/alarm/sse/TestController.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/static/mappers/alarm/ScheduleQueryMapper.xml
Closes #2
- 매일 미달성한 할일 알림 발송
- #2
> feat : 매일 미달성한 할 일 알림 (#2)

- backend/src/main/java/com/pigma/harusari/alarm/command/service/AlarmService.java
- backend/src/main/java/com/pigma/harusari/alarm/command/service/AlarmServiceImpl.java
- backend/src/main/resources/static/mappers/alarm/ScheduleQueryMapper.xml
Closes #17 
- alarmService 구현체 구현
- #17
> feat : 알림 서비스 구현체 구현 #17

- backend/src/main/java/com/pigma/harusari/alarm/command/scheduler/AlarmScheduler.java
- backend/src/main/java/com/pigma/harusari/alarm/query/mapper/ScheduleQueryMapper.java
- backend/src/main/resources/static/mappers/alarm/ScheduleQueryMapper.xml
- backend/src/test/java/com/pigma/harusari/alarm/command/service/AlarmServiceImplTest.java
Closes #2 
- 미달성한 할일 1개에 대한 알림 -> 미달성한 할일 갯수 알림으로 변경
- #2
> fix : 미달성한 할일 1개에 대한 알림 -> 알림 갯수 알림으로 변경 #2

- backend/src/main/java/com/pigma/harusari/alarm/command/scheduler/AlarmScheduler.java
- backend/src/main/java/com/pigma/harusari/alarm/query/mapper/ScheduleQueryMapper.java
- backend/src/main/resources/static/mappers/alarm/ScheduleQueryMapper.xml
Closes #4 
- 매달 전체적인 달성률 알림 발송
- #4
> feat : 매달 전체적인 달성률 알림 발송 (#4)

- backend/src/main/java/com/pigma/harusari/alarm/command/scheduler/AlarmScheduler.java
- backend/src/main/java/com/pigma/harusari/alarm/query/controller/AlarmQueryController.java
- backend/src/main/java/com/pigma/harusari/alarm/query/dto/AlarmResponseDto.java
- backend/src/main/java/com/pigma/harusari/alarm/query/mapper/AlarmQueryMapper.java
- backend/src/main/java/com/pigma/harusari/alarm/query/service/AlarmQueryService.java
- backend/src/main/java/com/pigma/harusari/alarm/sse/SseController.java
- backend/src/main/java/com/pigma/harusari/alarm/sse/TestController.java
- backend/src/main/resources/mappers/alarm/AlarmQueryMapper.xml
- backend/src/main/resources/mappers/alarm/ScheduleQueryMapper.xml
Closes #27 
- 안 읽은 알림 목록 조회
- alarmMapper.xml, alarmScheduler 에 있는 member_uid -> member_id 로 변경
- #27
> feat : 안 읽은 알림 목록 조회

- backend/src/main/resources/mappers/statistics/StatisticsMapper.xml
Closes #33
- 카테고리 테이블의 컬럼명 변경에 따라 StatisticsMapper.xml에서 member_uid를 member_id로 변경
- #33
> refactor: 카테고리 테이블의 member_uid 컬럼명을 member_id로 변경 (#33)

- frontend/.prettierrc.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/assets/css/header.css
- frontend/src/components/layout/Header.vue
- frontend/src/features/main/mainApi.js
- frontend/src/features/main/router.js
- frontend/src/features/main/views/MainPageView.vue
- frontend/src/features/statistics/views/StatisticsView.vue
- frontend/src/features/user/router.js
- frontend/src/features/user/views/LoginView.vue
- frontend/src/lib/api.js
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/stores/userStore.js
Closes #55 
- 메인 페이지 구현
- 로그인 화면 구
- 최초 접속 시 로그인 화면으로 이동하도록 구현
- 로그인 시 메인페이지로 이동하도록 구현
- #55
> feat :  메인페이지 및 로그인 기능 구현

- frontend/src/App.vue
- frontend/src/components/layout/Header.vue
- frontend/src/features/category/components/CategoryCreateModal.vue
- frontend/src/features/category/views/CategoryView.vue
- frontend/src/features/user/router.js
- frontend/src/features/user/views/LoginView.vue
- frontend/src/features/user/views/SignupView.vue
- frontend/src/router/index.js
Closes #73 
- 카테고리 등록 / 수정 사용자 지정 색상 추가
- #73
> feat : 카테고리 등록 / 수정 사용자 지정 색상 추가

- backend/src/main/java/com/pigma/harusari/common/config/SecurityConfig.java
- backend/src/main/java/com/pigma/harusari/diary/query/dto/DiaryResponseDto.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/mappers/schedule/TaskScheduleQueryMapper.xml
- .yml파일 수정 
- .yml 파일 변경 되었습니다. notion에서 env 설정도 다시 해주세요
> refactor : .yml

- frontend/src/features/category/views/CategoryView.vue
- frontend/src/features/statistics/components/CategoryStatistics.vue
- frontend/src/features/statistics/components/DailyStatistics.vue
- frontend/src/features/statistics/components/MonthlyStatistics.vue
- frontend/src/features/statistics/statisticsApi.js
- frontend/src/features/statistics/views/StatisticsView.vue
Closes #98 
- 백엔드 api 호출 부 별도 api로 관리하도록 수정
- #98
> feat : 통계 api호출부 기능 수정

- backend/src/main/java/com/pigma/harusari/diary/query/controller/DiaryQueryController.java
- backend/src/main/java/com/pigma/harusari/diary/query/mapper/DiaryQueryMapper.java
- backend/src/main/java/com/pigma/harusari/diary/query/service/DiaryQueryService.java
- backend/src/main/java/com/pigma/harusari/diary/query/service/DiaryQueryServiceImpl.java
- backend/src/main/java/com/pigma/harusari/feedback/command/service/FeedbackCommandServiceImpl.java
- backend/src/main/java/com/pigma/harusari/feedback/exception/FeedbackErrorCode.java
- backend/src/main/java/com/pigma/harusari/feedback/exception/FeedbackException.java
- backend/src/main/java/com/pigma/harusari/feedback/exception/handler/FeedbackExceptionHandler.java
- backend/src/main/java/com/pigma/harusari/feedback/util/FeedbackPromptBuilder.java
- backend/src/main/resources/mappers/diary/DiaryQueryMapper.xml
Closes #96 
- 일일 회고 조회
- 피드백 예외처리
- #96
> Feature/diary 일일 회고 조회 및 피드백 예외 처리

- backend/Dockerfile
- frontend/Dockerfile
- frontend/nginx.conf
Closes #103 
- 프론트 프로젝트에 Dockerfile 생성
- 프론트 프로젝트에 nginx.conf 생성 
- 백엔드 프로젝트에 Dockerfile 생성 
- #103
> feat: 프론트, 백엔드 Dockerfile 및 nginx.conf 파일 생성

- backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/controller/AutomationScheduleController.java
- backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/dto/request/AutomationScheduleCreateRequest.java
- backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/service/AutomationScheduleServiceImpl.java
- backend/src/main/java/com/pigma/harusari/task/schedule/command/controller/ScheduleCommandController.java
Closes #111 
- RequestBody import 경로 수정
- #111
> fix: RequestBody import 경로 수정

- backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/dto/request/AutomationScheduleCreateRequest.java
- backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/service/AutomationScheduleService.java
- backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/service/AutomationScheduleServiceImpl.java
- backend/src/main/java/com/pigma/harusari/task/schedule/command/dto/request/ScheduleUpdateRequest.java
- backend/src/test/java/com/pigma/harusari/task/automationSchedule/command/controller/AutomationScheduleControllerTest.java
- backend/src/test/java/com/pigma/harusari/task/automationSchedule/command/service/AutomationScheduleServiceImplTest.java
- backend/src/test/java/com/pigma/harusari/task/automationSchedule/query/controller/AutomationScheduleQueryControllerTest.java
- backend/src/test/java/com/pigma/harusari/task/automationSchedule/query/service/AutomationScheduleQueryServiceImplTest.java
- backend/src/test/java/com/pigma/harusari/task/schedule/command/controller/ScheduleCommandControllerTest.java
- backend/src/test/java/com/pigma/harusari/task/schedule/command/service/ScheduleCommandServiceImplTest.java
- backend/src/test/java/com/pigma/harusari/task/schedule/query/controller/ScheduleQueryControllerTest.java
- backend/src/test/java/com/pigma/harusari/task/schedule/query/service/ScheduleQueryServiceImplTest.java
Closes #113 
- 일정 및 자동화 일정 테스트 코드 추가
- #113
> feat: 일정 및 자동화 일정 테스트 코드 추가

- backend/src/main/java/com/pigma/harusari/category/command/application/controller/CategoryCommandController.java
- backend/src/main/java/com/pigma/harusari/common/auth/controller/AuthController.java
- backend/src/main/java/com/pigma/harusari/common/oauth/controller/KakaoAuthController.java
- backend/src/main/java/com/pigma/harusari/diary/command/application/controller/DiaryCommandController.java
- backend/src/main/java/com/pigma/harusari/diary/query/controller/DiaryQueryController.java
- backend/src/main/java/com/pigma/harusari/user/command/controller/UserCommandController.java
- backend/src/main/java/com/pigma/harusari/user/infrastructure/email/controller/EmailAuthController.java
- backend/src/main/java/com/pigma/harusari/user/infrastructure/email/controller/PasswordResetController.java
- backend/src/main/java/com/pigma/harusari/user/query/controller/UserQueryController.java
- backend/src/test/java/com/pigma/harusari/category/command/application/controller/CategoryCommandControllerTest.java
Closes #109 
- 작업한 기능이나 변경 사항 간단히 적기
- 예: 로그인 API 구현
- main에 머지 시 필수로 설정해야 하는 사항을 작성 (없다면 섹션 삭제)
- 예: .env 수정, npm install, DDL 변경 등
- #109
> feat : Diary, user controller 스웨거 문서화

- frontend/index.html
- frontend/src/features/main/views/MainPageView.vue
- frontend/src/features/user/views/LoginView.vue
- hotfix : 로그인 시 리다이렉트 안되는 문제 해결
-
> hotfix : 로그인 시 리다이렉트 안되는 문제 해결

- backend/src/main/java/com/pigma/harusari/BackendApplication.java
- backend/src/main/java/com/pigma/harusari/common/auth/service/CustomUserDetailsService.java
- backend/src/main/resources/application.yml
Closes #122 
- userDetail 캐싱 처리
- #122
> fix : userDetail 캐싱 처리

- backend/src/main/java/com/pigma/harusari/category/command/domain/aggregate/Category.java
- backend/src/main/java/com/pigma/harusari/diary/command/application/controller/DiaryCommandController.java
- frontend/src/features/category/categoryApi.js
- frontend/src/features/category/components/CategoryActionModal.vue
- frontend/src/features/category/views/CategoryView.vue
- frontend/src/features/main/components/EditTaskModal.vue
- frontend/src/features/main/mainApi.js
- frontend/src/features/main/views/MainPageView.vue
Closes #124 
- 회고 수정 및 삭제 기능 구현
- 회고 데이터 수정 시 오늘이 아니면 버튼 조작 안보이게 수정
- #124
> feat : 회고 수정 및 삭제 / 과거 데이터 수정 불가 기능

- backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/service/AutomationScheduleServiceImpl.java
> refactor: 자동화 일정 생성 로직 수정

- README.md
Closes #149 
- README.md 회고 등 수정
- #149
> docs: README.md 회고 등 수정

- README.md
Closes: #148 
- k8s-deploy-all.sh를 실행하는 코드 삭제
- 불필요한 이모지 제거
- #148
> docs: jenkins 파이프라인에서 불필요한 코드 삭제
